---
title: "R Notebook"
output: html_notebook
---

## GDPについて考えてみよう
国内総生産(GDP)は、Gross Domestic Productの頭文字をとって「GDP」と呼ばれている。
GDPは、ある国（例えば日本）の一定期間（四半期ごとあるいは1年間）の経済活動を記述する尺度である。
この章では、GDPの実際のデータを見ることでGDPの意味を考えてみたいと思う。

### GDPの歴史

### 供給面から見たGDP

日本で生産を行う企業がに作り出した財とサービスの総量を
産出額と言う。産出額には、最終製品を生み出すために企業間で取引した財やサービスが含まれている。例えば、自動車の生産を考えてみると良い。自動車を作るために、タイヤのゴムやフロントガラス、ボディに使う鉄鋼など、無数の部品が使われており、それらの部品は、自動車会社以外の会社が生産したものである。このように企業間で取引された財・サービスを中間投入と言う。GDPは、産出額から中間投入を引いた値のことで、付加価値と呼ばれている。また、中間投入には、企業が使う光熱費や運送費も含まれる。

企業会計では、産出額を「「売上」、中間投入を「減価」と呼び、売上から減価を引いた額を「売上総利益」と呼ぶ。国内総生産は、国内企業の売上総利益の合計だと考えることができる。


国内総生産は、さらに、次の４つの項目に分類される。労働者に対する賃金や給与の総額ある「雇用者報酬」、企業の利益である「営業余剰・混合所得」、消費税や関税などの「間接税」、企業設備の減価償却をあらわす「固定資本減耗」の４つの項目の合計額である。

資本主義経済は、資本家が保有する資本（生産設備や店舗、輸送機器など）を使って、労働者が生産活動を行うシステムのことである。供給面から見たGDPは、資本主義経済がどのような形で財・サービスを分配しているかを表していると言える。

雇用者報酬は、労働者（この中には企業の経営者も含まれる）が受け取る所得の合計である。
GDPに占める雇用者報酬の割合を労働分配率と呼んでいる。労働分配率は、生産活動が労働者にどの程度還元されているかを考える上で重要である。近年、日本を含む世界的な傾向として、労働分配率が低下していることが問題になっている。この問題は、経済成長の問題を考える章でもう一度取り上げる。

「営業余剰・混合所得」は、企業が手にする純利益のことである。企業の内部留保つまり貯蓄や株主(資本家）に対する配当、企業が保有しているなどが、営業余剰・が手にする所得である。営業余剰は、大企業の純利益、混合所得は中小零細企業の純利益である。

税金の内、間接税だけを別に集計している。間接税（特に、消費税）は、計算のルールが細かく決まっているので、集計することが難しい。

最後の固定資本減耗は、資本の償却分のことで、壊れた資本の更新やメンテナンス費用に対応する。

