---
title: "経済学でデータサイエンス(仮題)"
output: html_notebook
---

### １．GDPについて考えてみよう。
国内総生産（GDP）は、一国の経済活動を表す代表的な経済指標である。GDPのデータを正しく使うために、まず、GDPがどのようにデータを集めているかを知る必要がある。

「付加価値」の合計　

購入者価格でのGDPは、その経済圏に住むすべての生産者による付加価値総額の合計に、製品税と製品価格に含まれない補助金を加えたものです。また、製造された資産の減価償却費や天然資源の枯渇・劣化を控除することなく算出されています。データは現在の米ドルで表示されています。GDPのドル数値は、単年度の公式為替レートを使用して国内通貨から換算しています。公式為替レートが実際の為替取引に適用されるレートを反映していない少数の国については、別の換算係数を使用しています。

国際的にGDPを比較する際に注意する点は、

#### 1.1　GDPの歴史
#### 1.2　GDPの内容
#### 1.3　GDPの問題点
### ２．人口とGDPの関係について考えてみよう。
#### 2.1　世界人口の動向
#### 2.2　人口ボーナスと人口オーナス
#### 2.3  人口ボーナス（オーナス）とGDP
#### 2.4 スペンディングウェーブ
### ３．一人当たりGDPについて考えてみよう。
#### 3.1　GDPとGDP per Capitaの違い

#### GDP (current US$)
GDP at purchaser's prices is the sum of gross value added by all resident producers in the economy plus any product taxes and minus any subsidies not included in the value of the products. It is calculated without making deductions for depreciation of fabricated assets or for depletion and degradation of natural resources. Data are in current U.S. dollars. Dollar figures for GDP are converted from domestic currencies using single year official exchange rates. For a few countries where the official exchange rate does not reflect the rate effectively applied to actual foreign exchange transactions, an alternative conversion factor is used.

ID: NY.GDP.MKTP.CD
Source: World Bank national accounts data, and OECD National Accounts data files.
License:  CC BY-4.0 
Aggregation Method: Gap-filled total

##### Population, total
( 1 ) United Nations Population Division. World Population Prospects: 2022 Revision. ( 2 ) Census reports and other statistical publications from national statistical offices, ( 3 ) Eurostat: Demographic Statistics, ( 4 ) United Nations Statistical Division. Population and Vital Statistics Reprot ( various years ), ( 5 ) U.S. Census Bureau: International Database, and ( 6 ) Secretariat of the Pacific Community: Statistics and Demography Programme.


